"""initial schema

Revision ID: 28a1dc691df3
Revises: 
Create Date: 2026-07-24 22:45:17.566098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_cache',
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('eval_cp', sa.Integer(), nullable=False),
    sa.Column('best_move_uci', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fen', 'depth')
    )
    op.create_table('players',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('rating_snapshot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform in ('chesscom','lichess')", name='players_platform_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='players_platform_username_key')
    )
    op.create_table('games',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('player_id', app.models.GUID(), nullable=False),
    sa.Column('platform_game_id', sa.Text(), nullable=False),
    sa.Column('game_url', sa.Text(), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('time_class', sa.Text(), nullable=False),
    sa.Column('player_color', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('player_rating', sa.Integer(), nullable=True),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_eco', sa.Text(), nullable=True),
    sa.Column('opening_name', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("player_color in ('white','black')", name='games_player_color_check'),
    sa.CheckConstraint("result in ('win','loss','draw')", name='games_result_check'),
    sa.CheckConstraint("time_class in ('rapid','blitz')", name='games_time_class_check'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'platform_game_id', name='games_player_id_platform_game_id_key')
    )
    op.create_index('games_analyzed_idx', 'games', ['player_id', 'analyzed_at'], unique=False)
    op.create_index('games_player_idx', 'games', ['player_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('player_id', app.models.GUID(), nullable=False),
    sa.Column('games_analyzed', sa.Integer(), nullable=False),
    sa.Column('first_game_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_game_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Autogenerate can't diff this one on SQLite (it can't reflect an
    # expression-based descending index), so it's added here by hand per
    # Appendix 1: "reports (player_id, created_at desc)".
    op.create_index('reports_player_idx', 'reports', ['player_id', sa.text('created_at DESC')], unique=False)
    op.create_table('move_evals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', app.models.GUID(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('move_san', sa.Text(), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('eval_cp_before', sa.Integer(), nullable=False),
    sa.Column('eval_cp_after', sa.Integer(), nullable=False),
    sa.Column('cp_loss', sa.Integer(), nullable=False),
    sa.Column('best_move_san', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.CheckConstraint("classification in ('ok','inaccuracy','mistake','blunder','skipped')", name='move_evals_classification_check'),
    sa.CheckConstraint("phase in ('opening','middlegame','endgame')", name='move_evals_phase_check'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='move_evals_game_id_ply_key')
    )
    op.create_index('move_evals_class_idx', 'move_evals', ['game_id', 'classification'], unique=False)
    op.create_index('move_evals_game_idx', 'move_evals', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('move_evals_game_idx', table_name='move_evals')
    op.drop_index('move_evals_class_idx', table_name='move_evals')
    op.drop_table('move_evals')
    op.drop_index('reports_player_idx', table_name='reports')
    op.drop_table('reports')
    op.drop_index('games_player_idx', table_name='games')
    op.drop_index('games_analyzed_idx', table_name='games')
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('eval_cache')
    # ### end Alembic commands ###
